### ISSUE TITLE
Joining battle with 0 energy, no regeneration

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#182]
**Describe the bug**
Player joins a battle with 0 energy and no energy regeneration

**To Reproduce**
1. Unknown

**Expected behavior**
Player should join with correct energy amount and also regenerate their energy

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/126368488-aacc4b80-6298-4f7f-84cc-1f16ee8d7f13.png)

**Context:**
 - Character Name: Raistlin, Charles
 - Patch Version: 0.4.33
 - Game Build: 539

**Additional context**
"It starts with the bug in which you begin another battle immediately after another and u get stuck / ur character starts rubber banding" ~preni99

What would cause energy to not regenerate?

**Comment by phanxgames** [comment]
This is not related to energy. Energy remaining 0 means that the player is not connected to a battle properly at the start of battle, and missed the 100% energy packet, and therefore is not getting energy updates *because* they have 100% energy, and their energy no longer updates.

Possible solution:
Send 100% energy every so many seconds to make sure they get it.

**Comment by phanxgames** [comment]
Possible solution of sending resource state every few seconds should solve this issue. Will close until reported again.
